---
title: "Criminal Statistics in Toronto"
date: "2023-04-10" # `r format(Sys.time(), '%B %d, %Y')`
output: 
    html_document
---


<br>

## Introduction

Crime is a common social problem that affects communities worldwide. In Canada, Toronto has been the city with the highest crime rate, which includes violent and property crimes. The Toronto Police Service is the agency responsible for enforcing the law in the city, and it publishes criminal data on the [Public Safety Data Portal](https://data.torontopolice.on.ca/). This data includes information on the type of crime, location, and date of occurrence.

<br>

The inflation and unemployment rates are two economic indicators that reflect the financial well-being of a community. Inflation refers to the rate at which the general level of prices for goods and services is rising, and unemployment refers to the percentage of people who are not employed but are actively seeking work. Both indicators can have a significant impact on the daily lives of people, including their safety and security.

<br>

The purpose of this project is to analyze the crime statistics in the city of Toronto from 2014 to 2021, and investigate whether there is a correlation between the number of crimes in Toronto and changes in the inflation and unemployment rates over time. To achieve this, we will explore the crime data provided by the Toronto Police Service and compare it to the monthly [inflation rate](https://www.toronto.ca/city-government/data-research-maps/toronto-economy-labour-force-demographics/toronto-economic-dashboard/#detail/1.22) and [unemployment rates](https://www.toronto.ca/city-government/data-research-maps/toronto-economy-labour-force-demographics/toronto-economic-dashboard/#detail/1.02) obtained from the website of City of Toronto between January 2018 and January 2023. This analysis aims to shed light on the relationship between economic conditions and crime in Toronto, which can inform policies and strategies to improve public safety in the city.

<br>

Overall, we will provide an overview of the crime situation in the city of Toronto, including the types of crimes and their frequency. We will also discuss the inflation and unemployment rates in the city and how they have changed over time. Finally, we will present the results of our analysis and discuss the implications of the findings.

<br><hr><br>

### Access the Project

To view the complete pdf report, click [here](https://github.com/Chan-Y/JSC370_Final_Project/blob/main/docs/resources/files/FinalReport.pdf).

To watch a demonstration of this website, click [here](https://play.library.utoronto.ca/watch/7cbb48835688213f364d2ccdc415959f).

<br>
<br>
<br>
