---
title: "Interactive Visualizations"
subtitle: "For Assignment 5"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
        code_folding: show
---

```{r setup, message=FALSE, echo=FALSE, include=FALSE, eval=TRUE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
library(mapboxapi)
library(leaflet)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  # fig.width = 8, 
  fig.align = 'center',
  # fig.asp = 0.618,
  # out.width = "700px",
  class.source = "code-r")
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```



```{r load-data, include=FALSE, eval=TRUE}
source("resources/data/process_data.R")
```
<br>

This is my JSC370 Final Project website. I will showcase a few interactive visuals here.

<br>



## R Code {.tabset}

### Lineplot for Rates

```{r class.source = 'foldable'}
# Compare inflation and unemployment rate
plt1 <- rate_data %>% 
  plot_ly(
    x = ~ month_date,
    hoverinfo = "text",
    text = ~ paste(
      month.abb[month], year, "\n\t",
      "Inflation %: ", inflation, "\n\t",
      "Unemployment %: ", unemployment
    )
  ) %>% 
  add_lines(y = ~ inflation, name = "Inflation") %>% 
  add_lines(y = ~ unemployment, name = "Unemployment") %>% 
  layout(
    hovermode = "compare",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Rate", side = "left"),
    title = list(
      text = "Inflation Rate vs Unemployment Rate",
      font = list(size = 20),
      y = 0.95, x = 0.5, xanchor = 'center', yanchor = 'top'
    ),
    legend = list(
      title=list(text='Rate'),
      y = 0.68
    )
  )
```



### Mapview
```{r mapview, class.source='foldable', out.width="100%"}
# Group crime data by neighborhood
crime_by_neighb <- crime_data %>% 
  group_by(hood_id) %>% 
  summarise(
    longitude = mean(longitude),
    latitude = mean(latitude),
    neighbourhood = unique(neighbourhood),
    counts = length(unique(event_unique_id))
  )

# Read in Mapbox access token
MAPBOX_TOKEN <- paste(readLines("resources/files/.mb_token"), collapse="") 

# Plot mapview of nei
plt2 <- plot_mapbox(
    mode = 'scattermapbox'
  ) %>%
  add_markers(
    data = crime_by_neighb,
    y = ~ latitude,
    x = ~ longitude,
    size = ~ counts,
    sizemode = "area",
    color = ~ neighbourhood,
    hoverinfo = "text",
    text = ~ paste(
      neighbourhood, ": ", counts, " times"
    )
  ) %>% 
  layout(
    title = list(
      text = "Mapview of Crime Frequency in Neighborhoods",
      font = list(size = 16, color = "white"),
      y = 0.95, x = 0.5,
      xanchor = 'center', yanchor = 'top'
    ),
    mapbox = list(
      style = 'dark',
      zoom = 9,
      center = list(lat = median(crime_by_neighb$latitude),
                    lon = median(crime_by_neighb$longitude))
    ),
    # legend = list(orientation = 'h'),
    showlegend = FALSE
  ) %>% 
  config(mapboxAccessToken = MAPBOX_TOKEN)
```


```{r include=FALSE}

Toronto <- mb_isochrone(
  "City of Toronto",
  access_token = MAPBOX_TOKEN
) %>% 
  leaflet() %>%
  addMapboxTiles(style_id = "streets-v11",
                 username = "mapbox",
                 access_token = MAPBOX_TOKEN) %>%
  addPolygons()
  



library(mapboxapi)
mb_access_token(MAPBOX_TOKEN)
library(leaflet)

walk_5min <- mb_isochrone("2850 S University Dr, Fort Worth TX 76129",
                          profile = "walking",
                          time = 5,
                          access_token = MAPBOX_TOKEN)

leaflet(walk_5min) %>%
  addMapboxTiles(style_id = "streets-v11",
                 username = "mapbox",
                 access_token = MAPBOX_TOKEN) %>%
  addPolygons()


# plot_mapbox(maps::canada.cities) %>%
#   add_markers(
#     x = ~longitude, 
#     y = ~latitude, 
#     size = ~counts, 
#     color = ~country.etc,
#     colors = "Accent",
#     text = ~paste(neighbourhood, counts),
#     hoverinfo = "text"
#   )


# library(opendatatoronto)
# library(dplyr)
# 
# # get package
# package <- show_package("neighbourhoods")
# package
# 
# # get all resources for this package
# resources <- list_package_resources("neighbourhoods")
# 
# # identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
# datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
# 
# # load the first datastore resource as a sample
# data <- filter(datastore_resources, row_number()==1) %>% get_resource()
# data

```


### Scatterplot
```{r class.source = 'foldable'}
# balshdfadfj
```



## {- .unlisted}
<br>
<hr>
<br>
<br>

## Visualizations


```{r plt1, echo=FALSE}
plt1
```


- blah
- blah
- blah
- blah

```{r plt2, echo=FALSE}
plt2
```


- blah
- blah
- blah
- blah

```{r plt3, echo=FALSE}

```


<br>

<br>
<br>